apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  labels:
{{ include "spark.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
