apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appName }}-worker
  labels:
{{ include "spark.labels" . | indent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName }}
      app.kubernetes.io/component: worker
